plugins {
    id 'java'
    id 'jacoco'
    id 'application'
}

application {
    mainClass = 'ru.nsu.bogomolov.Main'
}

tasks.named('run') {
    standardInput = System.in
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}